
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.com.compiladores.trabalhofinal.AnlisadorSintatico;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MAIORQUE = 33;
  public static final int PONTVIRG = 5;
  public static final int CHAR = 8;
  public static final int CHARL = 35;
  public static final int DIFERENTE = 29;
  public static final int INT = 7;
  public static final int MAIORIGUAL = 31;
  public static final int NOT = 27;
  public static final int MENORIGUAL = 30;
  public static final int AND = 25;
  public static final int CHAVDIREI = 14;
  public static final int IGUAL = 28;
  public static final int PAREESQUE = 11;
  public static final int VIRG = 4;
  public static final int OR = 26;
  public static final int MAIS = 21;
  public static final int IF = 17;
  public static final int ID = 6;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int error = 1;
  public static final int MENOS = 3;
  public static final int PAREDIREI = 12;
  public static final int MOD = 24;
  public static final int VOID = 37;
  public static final int DIVISAO = 23;
  public static final int MENORQUE = 32;
  public static final int ELSE = 18;
  public static final int INTL = 34;
  public static final int FUNC = 10;
  public static final int WHILE = 16;
  public static final int FLOAT = 9;
  public static final int SETAR = 15;
  public static final int CHAVESQ = 13;
  public static final int VAR = 2;
  public static final int VEZES = 22;
  public static final int PRINT = 19;
  public static final int FLOATL = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "MENOS",
  "VIRG",
  "PONTVIRG",
  "ID",
  "INT",
  "CHAR",
  "FLOAT",
  "FUNC",
  "PAREESQUE",
  "PAREDIREI",
  "CHAVESQ",
  "CHAVDIREI",
  "SETAR",
  "WHILE",
  "IF",
  "ELSE",
  "PRINT",
  "RETURN",
  "MAIS",
  "VEZES",
  "DIVISAO",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "IGUAL",
  "DIFERENTE",
  "MENORIGUAL",
  "MAIORIGUAL",
  "MENORQUE",
  "MAIORQUE",
  "INTL",
  "CHARL",
  "FLOATL",
  "VOID"
  };
}

